# Rollback easytravel security change
---
-
  hosts: localhost
  connection: local
  name: "rollback easytravel security change"
  vars:
    easytravel_host: "ec2-34-201-102-216.compute-1.amazonaws.com"
    easytravel_plugin: CreditCardCheckError500
    easytravel_plugin_state: false
    configuration_tier: "CreditCardAuthorization"
    configuration_details: "SSL Certificate Update" #"F5 Network Configuration Change" #"Firewall Update"
    configuration_type: "Security" #"F5 Load Balancer" 
    configuration_new:  "1024 bit RSA" #"Network interface xyz" #"1024 bit RSA" #"Ports 9091, 9001, 9081, 9099 Allowed"
    configuration_old:  "2048 bit RSA" #"Network interface abc" #"Ports 9091, 9010, 9081 Allowed"
    configuration_remediation: "/api/v2/job_templates/12/launch/"
    dt_api_url: "https://fga13251.apps.dynatrace.com/"
    dt_api_token: "xx"
    
  tasks:
    -
      name: "initiate deployment change tasks (block)"
      block:
        -
          name: "call easytravel configuration UI to apply configuration change"
          uri:
            url: "http://{{ easytravel_host }}:8079/services/ConfigurationService/setPluginEnabled?name={{ easytravel_plugin }}&enabled={{ easytravel_plugin_state }}"
            status_code: 202
        -
          name: "push Dynatrace custom configuration event"
          uri:
            url: "{{ dt_api_url }}/v1/events?Api-Token={{ dt_api_token }}"
            method: POST
            headers:
              content-type: application/json
            body:
              eventType: CUSTOM_CONFIGURATION
              attachRules:
                tagRule:
                - meTypes:
                  - SERVICE
                  - PROCESS_GROUP_INSTANCE
                  tags:
                  - context: CONTEXTLESS
                    key: Tier
                    value: "{{ configuration_tier }}"
              source: Ansible Tower
              description: "{{ configuration_details }}"
              configuration: "{{ configuration_type }}"
              customProperties:
                Change Ticket: "{{ 99999999 | random(10000000, 10) }}"
                Change New: "{{ configuration_new }}"
                Change Old: "{{ configuration_old }}"
                Remediation: "{{ configuration_remediation }}"
                Service Now: "https://demo.service-now.com/nav?uri=change_request.do?id=892eb1124"
            body_format: json
            status_code: 200
